/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salary;

import java.awt.Color;
import java.text.DecimalFormat;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.SystemColor;
import java.awt.Font;

/**
 *
 * @author Febriansyah
 */
@SuppressWarnings("serial")
public class JFrame_1 extends javax.swing.JFrame {

    private final String result_text = "Hasil Honor";

    // III A
    private final int a3 = 1000000;
    // III B
    private final int b3;
    // III C
    private final int c3;
    // IV A
    private final int a4 = 2000000;
    // IV B
    private final int b4 = 2500000;
    // IV C
    private final int c4 = 3000000;

    /**
     * Creates new form JFrame_1
     */
    public JFrame_1() {
    	getContentPane().setFont(new Font("Arial", Font.PLAIN, 11));
    	setBackground(SystemColor.menu);
    	getContentPane().setBackground(SystemColor.menu);
        this.b3 = 1250000;
        this.c3 = 1500000;
        initComponents();
        setTitle("Aplikasi Perhitungan Gaji Karyawan");
    }

    /**
     * Fungsi untuk mendapatkan nilai
     * berdasarkan golongan tertentu.
     * 
     * @return int
     */
    public int GetSelectedRadioGolongan() {
        if (radio_gol_3a.isSelected()) {
            return a3;
        } else if (radio_gol_3b.isSelected()) {
            return b3;
        } else if (radio_gol_3c.isSelected()) {
            return c3;
        } else if (radio_gol_4a.isSelected()) {
            return a4;
        } else if (radio_gol_4b.isSelected()) {
            return b4;
        } else if (radio_gol_4c.isSelected()) {
            return c4;
        } else {
            return 0;
        }
    }

    /**
     * Fungsi untuk mendapatkan Tunjangan
     * bagi yang sudah menikah.
     * 
     * @return int
     */
    public int GetSelectedBoxTunjangan() {
        String perkawinan = cb_perkawinan.getSelectedItem().toString();
        if (perkawinan.equals("Menikah")) {
            return 1000000;
        } else {
            return 0;
        }
    }
    
    /**
     * Membuat angka menjadi ada comma nya
     * 
     * @param number
     * @return string
     */
    public String NumberFormatter(int number) {
    	String num_to_string = Integer.toString(number);
    	Double amount = Double.parseDouble(num_to_string);
    	DecimalFormat formatter = new DecimalFormat("#,###");
		return formatter.format(amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(SystemColor.menu);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Arial", Font.PLAIN, 12));
        form_nik = new javax.swing.JTextField();
        form_nik.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Arial", Font.PLAIN, 12));
        form_nama = new javax.swing.JTextField();
        form_nama.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Arial", Font.PLAIN, 12));
        form_alamat = new javax.swing.JTextField();
        form_alamat.setFont(new Font("Arial", Font.PLAIN, 12));
        cb_agama = new javax.swing.JComboBox < > ();
        cb_agama.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gender_male = new javax.swing.JRadioButton();
        radio_gender_male.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gender_female = new javax.swing.JRadioButton();
        radio_gender_female.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_3a = new javax.swing.JRadioButton();
        radio_gol_3a.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_3b = new javax.swing.JRadioButton();
        radio_gol_3b.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_4a = new javax.swing.JRadioButton();
        radio_gol_4a.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_4b = new javax.swing.JRadioButton();
        radio_gol_4b.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_3c = new javax.swing.JRadioButton();
        radio_gol_3c.setFont(new Font("Arial", Font.PLAIN, 12));
        radio_gol_4c = new javax.swing.JRadioButton();
        radio_gol_4c.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Arial", Font.PLAIN, 12));
        cb_perkawinan = new javax.swing.JComboBox < > ();
        cb_perkawinan.setFont(new Font("Arial", Font.PLAIN, 12));
        btn_process = new javax.swing.JButton();
        btn_process.setFont(new Font("Arial", Font.PLAIN, 12));
        btn_reset = new javax.swing.JButton();
        btn_reset.setFont(new Font("Arial", Font.PLAIN, 12));
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(SystemColor.menu);
        label_hasil = new javax.swing.JLabel();
        label_hasil.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setFont(new Font("Arial", Font.PLAIN, 12));
        result_gaji = new javax.swing.JLabel();
        result_gaji.setFont(new Font("Arial", Font.BOLD, 12));
        result_tunjangan = new javax.swing.JLabel();
        result_tunjangan.setFont(new Font("Arial", Font.BOLD, 12));
        result_total = new javax.swing.JLabel();
        result_total.setFont(new Font("Arial", Font.BOLD, 12));
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel17 = new javax.swing.JLabel();
        jLabel17.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel18 = new javax.swing.JLabel();
        jLabel18.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel19 = new javax.swing.JLabel();
        jLabel19.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_nik = new javax.swing.JLabel();
        hasil_nik.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_nama = new javax.swing.JLabel();
        hasil_nama.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_alamat = new javax.swing.JLabel();
        hasil_alamat.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_agama = new javax.swing.JLabel();
        hasil_agama.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_gender = new javax.swing.JLabel();
        hasil_gender.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_golongan = new javax.swing.JLabel();
        hasil_golongan.setFont(new Font("Arial", Font.PLAIN, 12));
        hasil_perkawinan = new javax.swing.JLabel();
        hasil_perkawinan.setFont(new Font("Arial", Font.PLAIN, 12));
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Arial", Font.PLAIN, 12));
        error_message = new javax.swing.JLabel();
        error_message.setFont(new Font("Arial", Font.PLAIN, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Data Pegawai");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));

        jLabel2.setText("NIK (Nomor Induk Kependudukan)");

        form_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_nikActionPerformed(evt);
            }
        });
        form_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_nikKeyTyped(evt);
            }
        });

        jLabel3.setText("Nama");

        form_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_namaActionPerformed(evt);
            }
        });
        form_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_namaKeyTyped(evt);
            }
        });

        jLabel4.setText("Alamat");

        form_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_alamatActionPerformed(evt);
            }
        });

        cb_agama.setEditable(false);
        cb_agama.setModel(new javax.swing.DefaultComboBoxModel < > (new String[] {
            "Islam",
            "Kristen",
            "Katholik",
            "Hindu",
            "Buddha"
        }));

        jLabel5.setText("Agama");

        jLabel6.setText("Jenis Kelamin");

        buttonGroup2.add(radio_gender_male);
        radio_gender_male.setSelected(true);
        radio_gender_male.setText("Laki - Laki");
        radio_gender_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gender_maleActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_gender_female);
        radio_gender_female.setText("Perempuan");
        radio_gender_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gender_femaleActionPerformed(evt);
            }
        });

        jLabel7.setText("Golongan");

        buttonGroup1.add(radio_gol_3a);
        radio_gol_3a.setSelected(true);
        radio_gol_3a.setText("III A");
        radio_gol_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_3aActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gol_3b);
        radio_gol_3b.setText("III B");
        radio_gol_3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_3bActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gol_4a);
        radio_gol_4a.setText("IV A");
        radio_gol_4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_4aActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gol_4b);
        radio_gol_4b.setText("IV B");
        radio_gol_4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_4bActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gol_3c);
        radio_gol_3c.setText("III C");
        radio_gol_3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_3cActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_gol_4c);
        radio_gol_4c.setText("IV C");
        radio_gol_4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gol_4cActionPerformed(evt);
            }
        });

        jLabel8.setText("Status Perkawinan");

        cb_perkawinan.setEditable(false);
        cb_perkawinan.setModel(new javax.swing.DefaultComboBoxModel < > (new String[] {
            "Menikah",
            "Belum Menikah"
        }));

        btn_process.setBackground(new java.awt.Color(153, 255, 153));
        btn_process.setText("Proses");
        btn_process.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_processMouseClicked(evt);
            }
        });
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(255, 204, 51));
        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(form_nama)
                    .addComponent(form_nik)
                    .addComponent(cb_perkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radio_gol_3c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_gol_4c))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radio_gol_3b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_gol_4b))
                    .addComponent(radio_gender_female)
                    .addComponent(radio_gender_male)
                    .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radio_gol_3a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_gol_4a))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_process)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(form_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radio_gender_male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_gender_female)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(radio_gol_3a)
                    .addComponent(radio_gol_4a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_gol_3b)
                    .addComponent(radio_gol_4b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_gol_3c)
                    .addComponent(radio_gol_4c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_perkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_process)
                    .addComponent(btn_reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, null));

        label_hasil.setText("Belum Ada Hasil");

        jLabel10.setText("Gaji");

        jLabel11.setText("Tunjangan");

        jLabel12.setText("Total");

        result_gaji.setText("-");

        result_tunjangan.setText("-");

        result_total.setText("-");

        jLabel13.setText("NIK");

        jLabel14.setText("Nama");

        jLabel15.setText("Alamat");

        jLabel16.setText("Agama");

        jLabel17.setText("Jenis Kelamin");

        jLabel18.setText("Golongan");

        jLabel19.setText("Status Perkawinan");

        hasil_nik.setText("-");

        hasil_nama.setText("-");

        hasil_alamat.setText("-");

        hasil_agama.setText("-");

        hasil_gender.setText("-");

        hasil_golongan.setText("-");

        hasil_perkawinan.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(result_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_hasil)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hasil_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(hasil_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasil_agama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasil_gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasil_golongan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasil_perkawinan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result_tunjangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasil_nik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(result_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_hasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result_tunjangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(result_gaji)
                        .addComponent(result_total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hasil_nik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hasil_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(hasil_alamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(hasil_agama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hasil_gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(hasil_golongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(hasil_perkawinan))
                .addContainerGap())
        );

        jLabel9.setText("Pesan Sistem :");

        error_message.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel9)
        								.addComponent(error_message))
        							.addGap(0, 294, Short.MAX_VALUE))))
        				.addComponent(jLabel1))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        					.addGap(18)
        					.addComponent(jLabel9)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(error_message)
        					.addGap(83))))
        );
        getContentPane().setLayout(layout);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btn_processActionPerformed
        String nik = form_nik.getText();
        String nama = form_nama.getText();
        String alamat = form_alamat.getText();
        String agama = cb_agama.getSelectedItem().toString();
        String gender;

        if (nik.equals("")) {
            error_message.setForeground(Color.RED);
            error_message.setText("Form NIK Wajib Diisi !!");
        } else if (nama.equals("")) {
            error_message.setForeground(Color.RED);
            error_message.setText("Form Nama Wajib Diisi !!");
        } else if (alamat.equals("")) {
            error_message.setForeground(Color.RED);
            error_message.setText("Form Alamat Wajib Diisi !!");
        } else {
        	error_message.setForeground(Color.GREEN);
            error_message.setText("Semua Form Valid");
        	
            label_hasil.setForeground(Color.blue);
            label_hasil.setText(result_text);
            
            result_gaji.setText(this.NumberFormatter(this.GetSelectedRadioGolongan()));
            
            result_tunjangan.setText(this.NumberFormatter(this.GetSelectedBoxTunjangan()));
            
            result_total.setText(this.NumberFormatter(this.GetSelectedRadioGolongan() + this.GetSelectedBoxTunjangan()));

            // hasil sadaya
            hasil_nik.setText(nik);
            hasil_nama.setText(nama);
            hasil_alamat.setText(alamat);
            hasil_agama.setText(agama);
            if (radio_gender_male.isSelected()) {
                gender = "Laki - Laki";
            } else {
                gender = "Perempuan";
            }
            hasil_gender.setText(gender);

            if (this.GetSelectedRadioGolongan() == a3) {
                hasil_golongan.setText("III A");
            } else if (this.GetSelectedRadioGolongan() == b3) {
                hasil_golongan.setText("III B");
            } else if (this.GetSelectedRadioGolongan() == c3) {
                hasil_golongan.setText("III C");
            } else if (this.GetSelectedRadioGolongan() == a4) {
                hasil_golongan.setText("IV A");
            } else if (this.GetSelectedRadioGolongan() == b4) {
                hasil_golongan.setText("IV B");
            } else if (this.GetSelectedRadioGolongan() == c4) {
                hasil_golongan.setText("IV C");
            }

            if (this.GetSelectedBoxTunjangan() == 1000000) {
                hasil_perkawinan.setText("Menikah");
            } else {
                hasil_perkawinan.setText("Belum Menikah");
            }
        }
    } //GEN-LAST:event_btn_processActionPerformed

    private void radio_gol_4cActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_4cActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_4cActionPerformed

    private void radio_gol_3cActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_3cActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_3cActionPerformed

    private void radio_gol_4bActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_4bActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_4bActionPerformed

    private void radio_gol_4aActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_4aActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_4aActionPerformed

    private void radio_gol_3bActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_3bActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_3bActionPerformed

    private void radio_gol_3aActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gol_3aActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gol_3aActionPerformed

    private void radio_gender_femaleActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gender_femaleActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gender_femaleActionPerformed

    private void radio_gender_maleActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_radio_gender_maleActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_radio_gender_maleActionPerformed

    private void form_namaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_form_namaActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_form_namaActionPerformed

    private void form_nikActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_form_nikActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_form_nikActionPerformed

    private void form_alamatActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_form_alamatActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_form_alamatActionPerformed

    private void btn_processMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_btn_processMouseClicked

    } //GEN-LAST:event_btn_processMouseClicked

    private void form_nikKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_form_nikKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    } //GEN-LAST:event_form_nikKeyTyped

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_btn_resetMouseClicked
        System.exit(0);
    } //GEN-LAST:event_btn_resetMouseClicked

    private void form_namaKeyTyped(java.awt.event.KeyEvent evt) { //GEN-FIRST:event_form_namaKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //            evt.consume();
        } else {
            evt.consume();
        }
    } //GEN-LAST:event_form_namaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox < String > cb_agama;
    private javax.swing.JComboBox < String > cb_perkawinan;
    private javax.swing.JLabel error_message;
    private javax.swing.JTextField form_alamat;
    private javax.swing.JTextField form_nama;
    private javax.swing.JTextField form_nik;
    private javax.swing.JLabel hasil_agama;
    private javax.swing.JLabel hasil_alamat;
    private javax.swing.JLabel hasil_gender;
    private javax.swing.JLabel hasil_golongan;
    private javax.swing.JLabel hasil_nama;
    private javax.swing.JLabel hasil_nik;
    private javax.swing.JLabel hasil_perkawinan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_hasil;
    private javax.swing.JRadioButton radio_gender_female;
    private javax.swing.JRadioButton radio_gender_male;
    private javax.swing.JRadioButton radio_gol_3a;
    private javax.swing.JRadioButton radio_gol_3b;
    private javax.swing.JRadioButton radio_gol_3c;
    private javax.swing.JRadioButton radio_gol_4a;
    private javax.swing.JRadioButton radio_gol_4b;
    private javax.swing.JRadioButton radio_gol_4c;
    private javax.swing.JLabel result_gaji;
    private javax.swing.JLabel result_total;
    private javax.swing.JLabel result_tunjangan;
    // End of variables declaration//GEN-END:variables
}